/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getAutoDriveSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-auto-drive',
    description: '自动驱动引擎（Auto-Opt）。设定目标和量化标准后 AI 自主驱动完整 OpenSpec 工作流循环。当用户想要自动迭代优化时使用。',
    instructions: `Auto-Opt 自动驱动引擎。设定目标和量化标准后，AI 自主驱动完整的 OpenSpec 工作流循环。

## 启动序列

1. 收集用户的优化目标和量化标准
2. 确认当前项目状态和可用资源
3. 制定自动驱动计划

## 配置收集

使用 AskUserQuestion 收集以下信息：
- **目标**：要优化或实现什么
- **量化标准**：如何衡量成功（测试通过率、性能指标等）
- **迭代次数上限**：最多执行多少次循环
- **门控级别**：none / design / all

## 引擎循环

每次迭代执行以下阶段：

**Phase 1 - 分析**：评估当前状态，确定改进方向

**Phase 2 - 探索**：使用 openspec-explore 探索方案并收敛设计

**Phase 3 - 规划**：使用 openspec-plan 创建变更

**Phase 4 - 实施**：使用 openspec-implement 逐项实施

**Phase 5 - 验证**：使用 openspec-verify 三维验证

**Phase 6 - 度量**：运行量化标准，检查是否达标

**Phase 7 - 决策**：达标则完成，否则进入下一次迭代

## 门控

| 级别 | 行为 |
|------|------|
| none | 完全自主，不暂停询问用户 |
| design | 在设计阶段暂停等待用户确认 |
| all | 在每个阶段转换时暂停等待确认 |

## 卡住恢复

当连续 2 次迭代没有改进时：
- 回退到上一个稳定状态
- 尝试完全不同的方案
- 如果仍然卡住，暂停并向用户求助

## 完成条件

- 量化标准达标，或
- 达到迭代次数上限，或
- 用户手动停止

## 退出契约

- 输出优化摘要，包含每次迭代的度量结果
- 输出最终状态和改进幅度
- 提供后续优化建议`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getAutoDriveCommandTemplate(): CommandTemplate {
  return {
    name: 'OpenSpec: 自动驱动',
    description: '启动自动驱动引擎，AI 自主驱动完整 OpenSpec 工作流循环',
    category: '工作流',
    tags: ['workflow', 'auto', 'optimize', 'iterate'],
    content: `启动 Auto-Opt 自动驱动引擎。

设定优化目标和量化标准后，AI 将自主驱动完整的 OpenSpec 工作流循环，包括脑暴、规划、实施、验证和度量。

**输入**：目标描述和量化标准
**输出**：优化后的代码和度量报告`,
  };
}
