/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getAutoDriveSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-auto-drive',
    description: '自动驱动引擎（Auto-Opt）。设定目标和量化标准后 AI 自主驱动完整 OpenSpec 工作流循环。当用户想要自动迭代优化时使用。',
    instructions: `Auto-Opt 自动驱动引擎。设定目标和量化标准后，AI 自主驱动完整的 OpenSpec 工作流循环。

## 启动序列

1. 收集用户的优化目标和量化标准
2. 确认当前项目状态和可用资源
3. 制定自动驱动计划

## 配置收集

使用 AskUserQuestion 收集以下信息：
- **目标**：要优化或实现什么
- **量化标准**：如何衡量成功（测试通过率、性能指标等）
- **迭代次数上限**：最多执行多少次循环
- **门控级别**：none / design / all

## 记录机制

每次迭代和最终完成时，将结果写入 \`.aiknowledge/auto-drive/<change-name>/\`：

\`\`\`
.aiknowledge/auto-drive/
└── <change-name>/
    ├── iter-01.md   ← 每轮 Phase 7 完成后写入
    ├── iter-02.md
    └── summary.md   ← 退出契约触发时生成
\`\`\`

**iter-N.md 格式**（文件名两位数补零，如 iter-01.md）：

\`\`\`markdown
# 第 N 轮迭代

**时间**：YYYY-MM-DD HH:MM
**量化指标**：目标值 X，本轮实测 Y，差距 Z

### 本轮方案

explore/plan 阶段收敛的核心决策（1-3 句）

### verify 发现

- [CRITICAL/WARNING/SUGGESTION] 问题描述

### 决策

达标 / 继续下一轮 / 卡住回退

### 卡住原因（如有）

说明连续 2 轮无改进的表现和回退策略
\`\`\`

**summary.md 格式**：

\`\`\`markdown
# Auto-Drive 摘要：<change-name>

**总轮次**：N
**最终状态**：达标 / 超出迭代上限 / 手动停止
**目标**：<用户设定的优化目标>
**量化标准**：<达标条件>

### 指标趋势

| 轮次 | 实测值 | 达标 |
|------|--------|------|
| 1    | Y1     | ✗    |
| 2    | Y2     | ✓    |

### 关键转折

- 第 N 轮：<什么决策带来了突破或停滞>

### 参考文件

- [第 1 轮](iter-01.md)
- [第 N 轮](iter-N.md)
\`\`\`

## 引擎循环

每次迭代执行以下阶段：

**Phase 1 - 分析**：评估当前状态，确定改进方向

**Phase 2 - 探索**：使用 openspec-explore 探索方案并收敛设计

**Phase 3 - 规划**：使用 openspec-plan 创建变更（生成 proposal + design + specs），plan-review 通过后由 openspec-tasks 生成 tasks，task-analyze 通过后进入实施

**Phase 4 - 实施**：使用 openspec-implement 逐项实施

**Phase 5 - 验证**：使用 openspec-verify 三维验证

**Phase 6 - 度量**：运行量化标准，检查是否达标；度量完成后立即写入 iter-N.md（N 为当前轮次，两位数补零），记录：本轮实测值、本轮方案摘要（来自 Phase 2-3）、verify 发现（来自 Phase 5）、达标与否

**Phase 7 - 决策**：达标则完成，否则进入下一次迭代

## 门控

| 级别 | 行为 |
|------|------|
| none | 完全自主，不暂停询问用户 |
| design | 在设计阶段暂停等待用户确认 |
| all | 在每个阶段转换时暂停等待确认 |

## 卡住恢复

当连续 2 次迭代没有改进时：
- 回退到上一个稳定状态
- 尝试完全不同的方案
- 如果仍然卡住，暂停并向用户求助

## 完成条件

- 量化标准达标，或
- 达到迭代次数上限，或
- 用户手动停止

## 退出契约

- 输出优化摘要，包含每次迭代的度量结果
- 输出最终状态和改进幅度
- 提供后续优化建议`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getAutoDriveCommandTemplate(): CommandTemplate {
  return {
    name: 'OpenSpec: 自动驱动',
    description: '启动自动驱动引擎，AI 自主驱动完整 OpenSpec 工作流循环',
    category: '工作流',
    tags: ['workflow', 'auto', 'optimize', 'iterate'],
    content: `启动 Auto-Opt 自动驱动引擎。

设定优化目标和量化标准后，AI 将自主驱动完整的 OpenSpec 工作流循环，包括脑暴、规划、实施、验证和度量。

**输入**：目标描述和量化标准
**输出**：优化后的代码和度量报告`,
  };
}
