/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getBrainstormSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-brainstorm',
    description: '交互式需求澄清和方案设计。当用户想要构建新功能、做出架构决策或启动非平凡任务时使用。',
    instructions: `脑暴 Skill。通过交互式对话澄清需求并设计方案。

## 启动序列

1. 执行 \`openspec-cn list --json\` 检查是否有相关的活跃变更
2. 读取 \`.aiknowledge/codemap/index.md\`（如存在），了解项目架构全貌
3. 阅读用户提出的需求或想法
4. 如果存在相关变更，阅读其产出物获取上下文
5. 如果涉及特定技术领域，读取 \`.aiknowledge/pitfalls/<领域>/index.md\` 了解已知踩坑

## 硬性门控

**在设计获得用户批准之前，绝不编写任何代码。** 这是不可协商的铁律。
- 不写产品代码
- 不写测试代码
- 不写脚手架代码
- 唯一允许的输出是 OpenSpec 产出物（提案、设计文档等）

## 流程

### 1. 理解
- 倾听用户的需求描述
- 提出澄清性问题，挖掘隐含假设
- 识别约束条件和非功能需求
- 调查代码库，了解现有架构和模式

### 2. 探索方案
- 提出至少 2-3 个可行方案
- 用 ASCII 图表可视化每个方案的架构
- 分析每个方案的优缺点和权衡
- 考虑边缘情况和潜在风险

### 3. 确认设计
- 与用户讨论并收敛到最终方案
- 确保用户明确批准设计
- 记录关键设计决策和理由

### 4. 转入规划
- 设计确认后，建议用户使用 openspec-plan 创建正式变更
- 提供清晰的需求摘要供规划使用

## 完成条件

- 用户已确认设计方向
- 明确了下一步转入哪个 skill

## 退出契约

- 输出设计摘要，包含问题定义、选定方案、关键决策
- 如果用户同意，过渡到 openspec-plan

## 关键原则

- **好奇心驱动** - 多问为什么，少做假设
- **可视化优先** - 用图表解释复杂概念
- **渐进收敛** - 从发散到收敛，不急于下结论
- **代码库感知** - 所有讨论都基于实际代码库上下文
- **尊重用户决策** - 提供建议但最终由用户决定`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
