/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

/**
 * ff-change skill 的指令文本。
 * 原 propose skill 已删除，该常量归属 ff-change 统一维护。
 */
export const FF_CHANGE_INSTRUCTIONS = `提案新变更 - 创建所有产出物并强制执行三道质量关卡后进入实施。

完整流程：
\`\`\`
创建 artifacts → [plan-review: spec↔plan] → [task-analyze: plan↔tasks] → 实施 → [verify: tasks↔code]
\`\`\`

---

**输入**：用户的请求应包含变更名称（kebab-case）或对他们想要构建内容的描述。

**步骤**

1. **如果没有提供明确的输入，询问他们想要构建什么**

   使用 **AskUserQuestion tool**（开放式，无预设选项）询问：
   > "您想要处理什么变更？请描述您想要构建或修复的内容。"

   根据他们的描述，推导出一个 kebab-case 名称（例如："add user authentication" → \`add-user-auth\`）。

   **重要提示**：在不了解用户想要构建什么的情况下，请勿继续。

2. **创建变更目录**
   \`\`\`bash
   openspec-cn new change "<name>"
   \`\`\`
   这将在 \`openspec/changes/<name>/\` 创建一个带有 \`.openspec.yaml\` 的脚手架变更。

3. **获取产出物构建顺序**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以获取：
   - \`applyRequires\`: 实现前所需的产出物 ID 数组（例如：\`["tasks"]\`）
   - \`artifacts\`: 所有产出物及其状态和依赖项的列表

4. **按顺序创建产出物，并在关键节点执行强制审查**

   使用 **TodoWrite tool** 跟踪产出物的进度。

   按依赖顺序循环遍历产出物（没有待处理依赖项的产出物优先）：

   a. **对于每个 \`ready\`（依赖项已满足）的产出物**：
      - 获取指令：
        \`\`\`bash
        openspec-cn instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 指令 JSON 包括：
        - \`context\`：项目背景（对你的约束 - 不要包含在输出中）
        - \`rules\`：产出物特定规则（对你的约束 - 不要包含在输出中）
        - \`template\`：用于输出文件的结构
        - \`instruction\`：此产出物类型的 Schema 特定指导
        - \`outputPath\`：写入产出物的位置
        - \`dependencies\`：已完成的产出物，用于读取上下文
      - 读取任何已完成的依赖文件以获取上下文
      - 使用 \`template\` 作为结构创建产出物文件
      - 应用 \`context\` 和 \`rules\` 作为约束 - 但不要将它们复制到文件中
      - 显示简短进度："✓ 已创建 <artifact-id>"

   b. **[关卡1] design 生成后，立即执行 plan-review（spec↔plan 审查）**
      - 调用 **openspec-plan-review** skill
      - 如果审查未通过（有 TRACE_GAP 或 ORPHAN）：必须修正 design 后重审，**禁止继续生成 tasks**
      - 审查通过后，继续生成 tasks

   c. **[关卡2] tasks 生成后，立即执行 task-analyze（plan↔tasks 审查）**
      - 调用 **openspec-task-analyze** skill
      - 如果审查未通过（有 GAP、MISMATCH 或严重 QUALITY 问题）：必须修正 tasks 后重审，**禁止进入实施**
      - 审查通过后，继续实施

   d. **继续直到所有 \`applyRequires\` 产出物完成**
      - 创建每个产出物后，重新运行 \`openspec-cn status --change "<name>" --json\`
      - 检查 \`applyRequires\` 中的每个产出物 ID 在 artifacts 数组中是否具有 \`status: "done"\`
      - 当所有 \`applyRequires\` 产出物完成且关卡1、关卡2 均通过时，才能进入实施

   e. **如果产出物需要用户输入**（上下文不清楚）：
      - 使用 **AskUserQuestion tool** 进行澄清
      - 然后继续创建

5. **实施**
   - 调用 **openspec-apply-change** 或要求我实现
   - 所有任务完成后，**必须**执行关卡3

6. **[关卡3] 实施完成后，执行 verify（tasks↔code 验证）**
   - 调用 **openspec-verify-change** skill
   - 如果验证未通过：列出需修复的问题，修复后重新验证
   - 验证通过后，可以归档

7. **显示最终状态**
   \`\`\`bash
   openspec-cn status --change "<name>"
   \`\`\`

**输出**

完成所有关卡后，总结：
- 变更名称和位置
- 已创建产出物的列表及简要描述
- 三道关卡审查结果
- 提示："运行 \`/opsx:archive\` 归档变更。"

**产出物创建指南**

- 遵循每个产出物类型的 \`openspec-cn instructions\` 中的 \`instruction\` 字段
- Schema 定义了每个产出物应包含的内容 - 遵循它
- 在创建新产出物之前阅读依赖产出物以获取上下文
- 使用 \`template\` 作为输出文件的结构 - 填充其各个部分
- **重要提示**：\`context\` 和 \`rules\` 是对你的约束，而不是文件内容
  - 不要将 \`<context>\`、\`<rules>\`、\`<project_context>\` 块复制到产出物中
  - 这些引导你编写内容，但不应出现在输出中

**护栏**
- 创建实现所需的所有产出物（由 Schema 的 \`apply.requires\` 定义）
- 在创建新产出物之前始终阅读依赖产出物
- **三道关卡是强制的，不可跳过**：design 后必须 plan-review，tasks 后必须 task-analyze，实施后必须 verify
- 如果上下文极其不清楚，询问用户 - 但倾向于做出合理的决定以保持势头
- 如果同名变更已存在，询问用户是否要继续它或创建一个新的
- 在继续下一个之前，验证写入后每个产出物文件是否存在`;

export function getFfChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-ff-change',
    description: '快速创建实现所需的所有产出物。当用户想要快速创建实现所需的所有产出物，而不是逐个创建时使用。',
    instructions: FF_CHANGE_INSTRUCTIONS,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxFfCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: 快进',
    description: '创建变更、生成所有产出物并强制执行三道质量关卡（plan-review → task-analyze → verify）',
    category: '工作流',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `快速完成完整工作流：创建产出物 → plan-review → task-analyze → 实施 → verify。

**输入**：\`/opsx:ff\` 之后的参数是变更名称（kebab-case），或用户想要构建内容的描述。

**步骤**

1. **如果没有提供输入，询问他们想要构建什么**

   使用 **AskUserQuestion tool**（开放式，无预设选项）询问：
   > "您想要处理什么变更？请描述您想要构建或修复的内容。"

   根据他们的描述，推导出一个 kebab-case 名称（例如："add user authentication" → \`add-user-auth\`）。

   **重要提示**：在不了解用户想要构建什么的情况下，请勿继续。

2. **创建变更目录**
   \`\`\`bash
   openspec-cn new change "<name>"
   \`\`\`
   这将在 \`openspec/changes/<name>/\` 创建一个脚手架变更。

3. **获取产出物构建顺序**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以获取：
   - \`applyRequires\`: 实现前所需的产出物 ID 数组（例如：\`["tasks"]\`）
   - \`artifacts\`: 所有产出物及其状态和依赖项的列表

4. **按顺序创建产出物直到准备好应用**

   使用 **TodoWrite tool** 跟踪产出物的进度。

   按依赖顺序循环遍历产出物（没有待处理依赖项的产出物优先）：

   a. **对于每个 \`ready\`（依赖项已满足）的产出物**：
      - 获取指令：
        \`\`\`bash
        openspec-cn instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 读取任何已完成的依赖文件以获取上下文
      - 使用 \`template\` 作为结构创建产出物文件
      - 应用 \`context\` 和 \`rules\` 作为约束 - 但不要将它们复制到文件中
      - 显示简短进度："✓ 已创建 <artifact-id>"

   b. **继续直到所有 \`applyRequires\` 产出物完成**
      - 创建每个产出物后，重新运行 \`openspec-cn status --change "<name>" --json\`
      - 当所有 \`applyRequires\` 产出物完成时停止

   c. **如果产出物需要用户输入**（上下文不清楚）：
      - 使用 **AskUserQuestion tool** 进行澄清
      - 然后继续创建

5. **显示最终状态**
   \`\`\`bash
   openspec-cn status --change "<name>"
   \`\`\`

**输出**

完成所有产出物后，总结：
- 变更名称和位置
- 已创建产出物的列表及简要描述
- 三道关卡审查结果
- 完成后提示："运行 \`/opsx:archive\` 归档变更。"

**护栏**
- 创建实现所需的所有产出物（由 Schema 的 \`apply.requires\` 定义）
- 在创建新产出物之前始终阅读依赖产出物
- **三道关卡是强制的**：design 后 plan-review，tasks 后 task-analyze，实施后 verify
- 如果上下文极其不清楚，询问用户 - 但倾向于做出合理的决定以保持势头
- 如果同名变更已存在，询问用户是否要继续它或创建一个新的
- 在继续下一个之前，验证写入后每个产出物文件是否存在`
  };
}
