/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getPlanSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-plan',
    description: '创建 OpenSpec change 并生成全套 artifact（proposal/design/specs/tasks）。当需求已明确、准备进入规划阶段时使用。',
    instructions: `规划 Skill。创建 OpenSpec change 并生成完整的产出物集合。

## 启动序列

1. 确认需求已经过脑暴或探索阶段的澄清
2. 执行 \`openspec-cn list --json\` 检查是否已有相关变更
3. 读取 \`.aiknowledge/codemap/\` 中涉及模块的 overview.md 和 dependencies.md，了解模块边界和依赖
4. 读取 \`.aiknowledge/pitfalls/\` 中相关领域的 index.md，在设计中规避已知陷阱
5. 收集必要的上下文信息

## 流程

### 1. 创建变更
- 使用 \`openspec-cn new YYYY-MM-DD-<name>\` 创建新变更
- **变更名称必须带日期前缀**（如 \`2026-04-03-add-auth\`），便于按时间追溯
- 名称部分简洁、描述性强，使用 kebab-case

### 2. 指令循环
逐个生成以下产出物，每个都经过用户确认：

**proposal.md** - 提案
- 问题陈述和目标
- 范围界定（做什么、不做什么）
- 成功标准

**design.md** - 设计
- 架构方案和关键决策
- 接口定义和数据模型
- 依赖关系和集成点

**specs/** - 规格说明
- 按能力拆分的详细规格
- 每个 spec 包含输入、输出、行为描述
- 边缘情况和错误处理

**tasks.md** - 任务列表
- 将实施工作拆分为独立的、可测试的任务
- 每个任务有清晰的完成标准
- 任务按依赖关系排序

### 3. 任务质量检查
- 每个任务不超过 2 小时的工作量
- 每个任务有明确的验收标准
- 任务之间的依赖关系清晰

### 4. 逐个提交
- 每个产出物完成后单独提交到 git
- 提交信息遵循项目规范

## 完成条件

- 所有产出物已生成并获得用户确认
- 所有产出物已提交到 git
- 任务列表质量检查通过

## 退出契约

- 输出变更摘要，包含所有产出物的简要描述
- 建议转入 **openspec-plan-review** 审查规划一致性`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
