/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getShipSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-ship',
    description: '归档上线：sync delta specs、archive change、执行 git 操作。当代码审查通过后准备交付时使用。',
    instructions: `归档上线 Skill。完成最终的归档和上线流程，包括 sync delta specs、archive change 和 git 操作。

## 启动序列

1. 确认 openspec-review 审查已通过（无 CRITICAL 问题）
2. 确认所有测试通过
3. 确认所有变更已提交

## 流程

### 1. 预检
- 运行全量测试套件，确认全部通过
- 检查是否有未提交的变更
- 检查是否有未解决的 CRITICAL 审查问题

### 2. Sync Delta Specs
- 执行 \`openspec-cn sync\` 将变更中的 specs 同步到全局 specs 目录
- 确认同步结果正确

### 3. Archive
- 执行 \`openspec-cn archive <name>\` 归档变更
- 变更从 \`openspec/changes/\` 移动到 \`openspec/archive/\`
- 确认归档成功

### 4. Git 操作
- 提交归档变更
- 如果需要，创建 tag 标记版本
- 如果需要，推送到远程仓库

## 完成条件

- Delta specs 已同步
- 变更已归档
- 所有 git 操作完成

## 退出契约

- 输出上线摘要，包含变更名称、归档路径和 git 状态
- 确认工作流完整闭环`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
