/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getTaskAnalyzeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-task-analyze',
    description: '任务分析：检查 tasks 是否完整覆盖 design/specs 需求、是否与 design 一致。在 tasks 生成后、implement 之前使用。',
    instructions: `# 任务分析：plan↔tasks 一致性检查

## 硬性门控

**这是强制关卡。** 在本 skill 输出"可实施"结论之前，禁止进入 openspec-implement 或任何编码活动。

## 启动序列

1. 确认 git 工作区干净
2. \`openspec-cn status --change "<name>" --json\` 确认 tasks artifact 已生成
3. 确认 openspec-plan-review 已通过（spec↔plan 一致性已验证）
4. 读取 change 的全部 artifact：proposal.md、design.md、specs/、tasks.md

## 审查方式

使用 Agent tool 启动 subagent 进行独立审查。subagent 只读取产出物文件，不做任何修改。审查结果由 subagent 汇报，主 agent 汇总输出。

## 审查维度

### 需求覆盖（design/specs → tasks）
- 每个实施单元 [U1] 都必须落到至少一个 task
- 每条需求必须有至少一个带 [R1] 标签的 task 对应
- 每条 Given/When/Then 场景必须有对应的验证方式
- 标记未覆盖的需求为 **GAP**

### 设计一致性（design → tasks）
- design.md 中的架构决策是否在 tasks 中体现
- 技术选型是否与 task 实施方式匹配
- 模块划分是否与 task 粒度对齐
- task 是否使用 \`[R?][U?][test-first|characterization-first|direct]\` 标签
- 标记不一致为 **MISMATCH**

### tasks 质量检查
- 每个 task 是否有精确文件路径
- 每个 task 是否有明确的验证方式
- task 之间是否有隐含依赖未标注
- task 粒度是否合理（过大需拆分，过小可合并）
- 标记问题为 **QUALITY**

## 输出格式

\`\`\`
## 任务分析报告

### 覆盖矩阵
| 需求 | 实施单元 | 对应 Task | 状态 |
|------|----------|----------|------|
| R1 | U1 | Task N | ✓/GAP |

### 问题列表
[GAP] 需求 X / 单元 UY 无对应 task
[MISMATCH] design 决策 Y 与 task Z 实施方式冲突
[QUALITY] Task W 缺少 trace / 执行方式 / 验证方式

### 结论
可实施 / 需补充后实施
\`\`\`

## 完成条件

- 分析报告已输出
- 覆盖矩阵已完成
- 所有 GAP 和 MISMATCH 已列出

## 退出契约

- **如"可实施"**：必须转入 **openspec-implement**。这不是建议，是强制要求。
- **如"需补充"**：必须回到 **openspec-plan** 修正 tasks.md。禁止绕过直接进入实施。
- 所有发现已记录在分析报告中`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
