/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getTddSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-tdd',
    description: '测试先行铁律。强制红绿重构循环，自动探测多语言测试框架。任何需要编写产品代码的时刻必须使用。',
    instructions: `测试驱动开发 Skill。强制执行红绿重构循环，确保所有产品代码都有测试覆盖。

## 铁律

**先写测试，再写代码。没有例外。** 任何产品代码的编写都必须遵循 TDD 循环。如果发现自己在没有失败测试的情况下编写产品代码，立即停止。

## 启动序列

1. 确认当前任务的需求和验收标准
2. 探测项目使用的测试框架
3. 确认测试命令可以正常运行
4. 读取 \`.aiknowledge/pitfalls/\` 中与当前任务相关领域的 index.md，写测试时覆盖已知易错点

## 测试框架探测

| 项目标志文件 | 测试框架 |
|-------------|----------|
| CMakeLists.txt | gtest |
| pyproject.toml / setup.py | pytest |
| package.json | vitest / jest |
| build.gradle / pom.xml | JUnit |
| *.xcodeproj | XCTest |

## 红绿重构循环

### 红 - 写失败测试
1. 根据需求编写一个最小的失败测试
2. 运行测试，确认它失败（且失败原因正确）
3. 不要一次写多个测试

### 绿 - 写最少代码通过测试
1. 编写刚好能让测试通过的最少代码
2. 运行测试，确认它通过
3. 不要过度设计，不要提前优化

### 重构 - 改善代码质量
1. 在测试通过的保护下重构代码
2. 消除重复、改善命名、简化逻辑
3. 运行测试，确认重构没有破坏功能

## 完成条件

- 所有验收标准都有对应的测试
- 所有测试通过
- 代码已经过重构
- 测试覆盖了边缘情况

## 退出契约

- 所有新增/修改的代码已有对应测试
- 测试全部通过
- 变更已 git commit
- 输出总结：新增了哪些测试、覆盖了哪些行为

## 反模式

以下行为严格禁止：
1. 先写产品代码再补测试 - 参见 @anti-patterns.md
2. 写了测试但跳过红色阶段（测试一开始就通过）- 参见 @anti-patterns.md
3. 一次性写大量测试而不逐个循环 - 参见 @anti-patterns.md
4. 重构时不运行测试 - 参见 @anti-patterns.md
5. 用 mock 替代真实行为测试而导致假阳性 - 参见 @anti-patterns.md

## 合理化借口防护

| 借口 | 正确做法 |
|------|----------|
| "这个函数太简单了，不需要测试" | 简单函数也需要测试，因为它可能变复杂 |
| "我先写代码理清思路，再补测试" | 用测试来理清思路，这就是 TDD 的目的 |
| "测试框架还没配好" | 先配好测试框架再写代码 |
| "这是 UI 代码，不好测试" | 分离逻辑层，逻辑层必须测试 |
| "时间不够写测试了" | 没有测试的代码不算完成 |`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
