/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getVerifySkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-verify',
    description: '三维验证检查（完整性/正确性/一致性）。当实施完成或用户想要检查 change 质量时使用。增强版 verify-change。',
    instructions: `验证 Skill。对已完成的变更进行三维验证检查，确保质量达标。

## 启动序列

1. 读取当前变更的所有产出物（proposal/design/specs/tasks）
2. 读取实施的代码变更（git diff）
3. 运行所有测试确认通过

## 三维检查

### 完整性检查
- tasks.md 中的所有任务是否都已完成
- specs 中的所有需求是否都已实现
- 是否有遗漏的边缘情况
- 是否有未实现的错误处理

### 正确性检查
- 实现是否符合 design.md 的架构设计
- 代码行为是否满足 specs 中的规格说明
- 测试是否真正验证了业务逻辑
- 是否存在逻辑错误或数据不一致

### 一致性检查
- 代码风格是否与项目现有风格一致
- 命名约定是否遵循项目规范
- API 接口是否与设计文档一致
- 文档是否与实际实现同步更新

## 输出格式

生成验证报告，包含以下内容：

**验证记分卡**

| 维度 | 状态 | 得分 | 说明 |
|------|------|------|------|
| 完整性 | 通过/未通过 | x/10 | 具体说明 |
| 正确性 | 通过/未通过 | x/10 | 具体说明 |
| 一致性 | 通过/未通过 | x/10 | 具体说明 |

**问题清单** - 列出所有发现的问题及建议修复方案

## 完成条件

- 三维检查全部完成
- 验证报告已生成
- 所有 CRITICAL 问题已修复或记录

## 退出契约

- 输出验证报告
- **如果验证通过**：必须转入 **openspec-review** 进行代码审查。这不是建议，是强制要求。
- **如果验证未通过**：列出需要修复的问题，禁止继续后续流程。必须修复后重新执行 openspec-verify。`,
    license: 'MIT',
    compatibility: '需要 openspec CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
